version: "3"
services:
  # コンテナ
  # php-fpm
  php-fpm:
    image: laravel-php-fpm:7
    build: ./php-fpm/
    depends_on:
      - mysql
      - redis
    volumes:
      # Laravelのソースファイル
      - ../laravel:/var/www/html

  # nginx
  nginx:
    image: nginx:mainline-alpine
    depends_on:
      - php-fpm
    ports:
      - 80:80
    volumes:
      # nginxの設定ファイル
      - ./nginx/conf/laravel.conf:/etc/nginx/conf.d/default.conf
      # Laravelのソースファイル
      - ../laravel:/var/www/html

  # MySQL
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password # MySQLのrootパスワード
      # 以下に指定したDB名やユーザーは、MySQLコンテナの新規作成時に作成されます。
      MYSQL_DATABASE: laravel # DB名
      MYSQL_USER: laravel_user # ユーザー名
      MYSQL_PASSWORD: laravel_pass # パスワード
    ports:
      - 3306:3306
    volumes:
      # このマウント先に入れたシェルスクリプトは、コンテナ作成後自動的に実行されます。
      - ./mysql/init:/docker-entrypoint-initdb.d:ro
      # MySQLのデータファイル
      - mysql-data:/var/lib/mysql

  # Redis
  redis:
    image: redis:alpine
    volumes:
      # Redisのデータファイル
      - redis-data:/data

  minio:
    image: minio/minio
    environment:
      MINIO_ACCESS_KEY: LARAVEL_MINIO_ACCESS_KEY # アクセスキー
      MINIO_SECRET_KEY: laravel_mino_hogefuga # シークレットキー
    ports:
      - 9000:9000
    command: server /data
    volumes:
      - minio-data:/data
# ネットワークはデフォルトのものを使用します。
#networks:
#  default:
#    driver: bridge

# データ用のボリューム
volumes:
  mysql-data:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local
